# config.yaml
training:
  root_dir: '/Users/vitsiozo/Code/Image/data'
  num_epochs: 10
  batch_size: 4
  num_classes: 34
  learning_rate: 0.001

model:
  type: 'SimpleFCN'

logger:
  experiment_name: 'Cityscapes_Semantic_Segmentation'
  project: 'cityscapes_project'
  entity: 'vitsiozo'
  models_dir: '/Users/vitsiozo/Code/Image/models'